import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";

Head

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["400","500","700"],
});

export const metadata: Metadata = {
  title: "Habit Zen",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
